controller_list:
  - name: fake_xarm_arm_controller
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
  - name: fake_xarm_gripper_controller
    joints:
      - gripper_joint1
      - gripper_joint2