xarm_arm:
  kinematics_solver: xarm_kinematics_plugin/XarmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # kinematics_solver_attempts: 3
  # solve_type: Distance
  # position_only_ik: true