xarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
    gains:
      arm_joint1: {p: 80.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint2: {p: 300.0, i: 0.2, d: 0.5, i_clamp: 0.0}
      arm_joint3: {p: 250.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint4: {p: 200.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  # gripper_controller:
  #   type: position_controllers/GripperActionController
  #   joint: gripper_joint1
